# Generated by Django 3.2.12 on 2025-02-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutypreference',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_preferences', to='exam.teacher'),
        ),
    ]
