# Generated by Django 5.0.1 on 2025-02-28 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_alter_dutypreference_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="pgm",
        ),
        migrations.AddField(
            model_name="course",
            name="dept_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam.department",
            ),
            preserve_default=False,
        ),
    ]
