# Generated by Django 3.2.12 on 2025-04-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_rename_is_present_studentexam_is_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattendance',
            name='course_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='examattendance',
            unique_together={('date', 'course_code')},
        ),
    ]
