# Generated by Django 3.2.12 on 2025-04-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_course_pgm_course_dept_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=20)),
                ('scribe_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dutyallotment',
            constraint=models.UniqueConstraint(fields=('teacher', 'date'), name='unique_teacher_duty_per_day'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examattendance'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
        ),
    ]
