# Generated by Django 3.2.12 on 2025-04-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20250410_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
