# Generated by Django 3.2.12 on 2025-04-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_studentexam_is_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentexam',
            old_name='is_present',
            new_name='is_absent',
        ),
    ]
